### ISSUE TITLE
issue compiling on a mac

### ISSUE THREAD

**Issue by qaisjp** [sztupy/luadec51#2]
I made an xcode proj for a mac "Terminal project" and used the language "C"
I downloaded the lua source files and drag/drop it to the Source files subdir in xcode and pressed ok
took the lua 5.1 source code and dragged and dropped it in the Source files subdir in xcode
build and run
screenie http://qs.lc/cx3
debug log http://pastebin.com/dNyMJhwu

**Comment by sztupy** [comment]
luadec should now compile fine with the supplied Makefile. I have also uploaded a binary build, that should hopefully work out of the box on OSX 10.9+
